/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimersIndexRouteImport } from './routes/timers.index'
import { Route as TimersTimerIdRouteImport } from './routes/timers.$timerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimersIndexRoute = TimersIndexRouteImport.update({
  id: '/timers/',
  path: '/timers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimersTimerIdRoute = TimersTimerIdRouteImport.update({
  id: '/timers/$timerId',
  path: '/timers/$timerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timers/$timerId': typeof TimersTimerIdRoute
  '/timers/': typeof TimersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timers/$timerId': typeof TimersTimerIdRoute
  '/timers': typeof TimersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timers/$timerId': typeof TimersTimerIdRoute
  '/timers/': typeof TimersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/timers/$timerId' | '/timers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/timers/$timerId' | '/timers'
  id: '__root__' | '/' | '/timers/$timerId' | '/timers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimersTimerIdRoute: typeof TimersTimerIdRoute
  TimersIndexRoute: typeof TimersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timers/': {
      id: '/timers/'
      path: '/timers'
      fullPath: '/timers/'
      preLoaderRoute: typeof TimersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timers/$timerId': {
      id: '/timers/$timerId'
      path: '/timers/$timerId'
      fullPath: '/timers/$timerId'
      preLoaderRoute: typeof TimersTimerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimersTimerIdRoute: TimersTimerIdRoute,
  TimersIndexRoute: TimersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
