/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TimersIndexRouteImport } from './routes/timers.index'
import { Route as TimersTimerIdRouteImport } from './routes/timers.$timerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TimersIndexRoute = TimersIndexRouteImport.update({
  id: '/timers/',
  path: '/timers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimersTimerIdRoute = TimersTimerIdRouteImport.update({
  id: '/timers/$timerId',
  path: '/timers/$timerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/timers/$timerId': typeof TimersTimerIdRoute
  '/timers/': typeof TimersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/timers/$timerId': typeof TimersTimerIdRoute
  '/timers': typeof TimersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/timers/$timerId': typeof TimersTimerIdRoute
  '/timers/': typeof TimersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/focus'
    | '/settings'
    | '/statistics'
    | '/timers/$timerId'
    | '/timers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/focus'
    | '/settings'
    | '/statistics'
    | '/timers/$timerId'
    | '/timers'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/focus'
    | '/settings'
    | '/statistics'
    | '/timers/$timerId'
    | '/timers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FocusRoute: typeof FocusRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  TimersTimerIdRoute: typeof TimersTimerIdRoute
  TimersIndexRoute: typeof TimersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timers/': {
      id: '/timers/'
      path: '/timers'
      fullPath: '/timers/'
      preLoaderRoute: typeof TimersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timers/$timerId': {
      id: '/timers/$timerId'
      path: '/timers/$timerId'
      fullPath: '/timers/$timerId'
      preLoaderRoute: typeof TimersTimerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FocusRoute: FocusRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  TimersTimerIdRoute: TimersTimerIdRoute,
  TimersIndexRoute: TimersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
